### ISSUE TITLE
Preface revision history

### ISSUE THREAD

**Issue by rhattersley** [cf-metadata/cf-conventions#14]
In the preface, the existing description of the revision history is no longer accurate.

In particular, if we are no longer using the pink, yellow, green highlighting scheme the following phrase no longer applies:

> Changes with provisional status use the following mark-up style: ...

Also, we need to consider if the following phrase is still accurate:

> See Appendix G, Revision History for the full revision history. 

Perhaps the following wording would be more appropriate?

> This document will be updated to reflect agreed changes to the standard and to correct mistakes according to the rules of [CF governance](http://cfconventions.org/governance.html). See [Revision History](http://cf-metadata.github.io/#revhistory) for the revision history prior to the move to GitHub. See [GitHub](https://github.com/cf-convention) for the subsequent revision history.

**Comment by rhattersley** [comment]
@JonathanGregory / @davidhassell / @rsignell-usgs / etc. - I'd love to know what you think...?

**Comment by JonathanGregory** [comment]
Yes, I agree, the text about the markup for provisional status should be omitted in this conversion of CF 1.6. However, the revision history should remain in App G, since that's how it is in this version. The committee decided that 1.6 should be migrated to the new format as it is (following your suggestion, Richard), and then 1.7 should be prepared in the new format. For 1.7, there is a ticket to move the revision history to App Z so that it's at the end! We have not discussed what to do after that. There could be a case for keeping the revision history in the document itself, but I think we ought to discuss that when we've got to 1.7.

Many thanks for your efforts. Jonathan

**Comment by rhattersley** [comment]
> I agree, the text about the markup for provisional status should be omitted in this conversion of CF 1.6.

Excellent - I'll trim that bit.

> the revision history should remain in App G

:+1: Completely agree - v1.6 should be as similar as possible.

**Comment by rhattersley** [comment]
NB. For the wording to match completely also requires #39 to be merged (to supply the "Appendix G, Revision History" text in the cross-reference.)
